name: CI - auth-service

on:
  push:
    branches: [main]
    paths:
      - "auth-service/**"
      - ".github/workflows/ci-auth-service.yml"
      - ".github/workflows/reusable-ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "auth-service/**"

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      service_name: auth-service
      language: go
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
